version: "3.4"

services:
  backend:
    build: backend
    image: backend
    volumes:
      - ./backend/:/app
    ports:
      - 3001:3001

  frontend:
    build: frontend
    image: frontend
    volumes:
      - ./frontend/:/app
    ports:
      - 3000:3000